apiVersion: v1
kind: ConfigMap
metadata:
    name: "{{ include "dev-gateway.fullname" . }}-config"
data:
    nginx.conf: |-
      user  nginx;
      worker_processes  1;

      error_log  /var/log/nginx/error.log warn;
      pid        /var/run/nginx.pid;

      events {
        worker_connections  1024;
      }

      http {
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        server {
          location / {
            root /data/www;
          }

          location /ambassador/ {
            proxy_pass http://ambassador-admin:8877/ambassador/;
          }

          location /kibana {
            rewrite ^/kibana/(.*)$ /$1 break;
            proxy_pass http://{{ .Release.Name }}-kibana:5601/;
          }
        }
      }
