apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      node-type: webserver
  template:
    metadata:
      labels:
        node-type: webserver
    spec:
      containers:
      - name: httpd
        image: corefantasy/ui
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
      imagePullSecrets:
      - name: docker-hub-credentials
