apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: NodePort
  ports:
   - protocol: TCP
     port: 31000
     targetPort: 80
     nodePort: 31000 # Matches port in the gateway target group and security group.
  selector:
    service: ambassador
