kibana:
  env:
    ELASTICSEARCH_URL: "http://elasticsearch-client:9201"  # Matches alias service in core-elasticsearch.
  nodeSelector:
    node-type: elk
  service:
    externalPort: 5601
  files:
    kibana.yml:
      server.name: kibana
      server.host: "0"
      server.basePath: /kibana  # For the dev gateway
