AWSTemplateFormatVersion: '2010-09-09'
Description: Creates certificates for the core-fantasy domains.
Metadata: {}
Parameters: {}
Resources:
  CoreDashFantasyCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "core-fantasy.com"
      SubjectAlternativeNames:
        - "*.core-fantasy.com"
      ValidationMethod: DNS
  CoreFantasyCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "corefantasy.com"
      SubjectAlternativeNames:
      - "*.corefantasy.com"
      ValidationMethod: DNS
Outputs:
  CoreDashFantasyCertificateARN:
    Description: "Core-Fantasy Certificate ARN"
    Value: !Ref "CoreDashFantasyCertificate"
    Export:
      Name: !Sub "CoreDashFantasy-Certificate-ARN"
  CoreFantasyCertificateARN:
    Description: "Core Fantasy Certificate ARN"
    Value: !Ref "CoreFantasyCertificate"
    Export:
      Name: !Sub "CoreFantasy-Certificate-ARN"
