AWSTemplateFormatVersion: '2010-09-09'
Description: Creates certificates for the core-fantasy domains.
Metadata: {}
Parameters: {}
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "*.core-fantasy.com"
      SubjectAlternativeNames:
        - "*.corefantasy.com"
      ValidationMethod: DNS
Outputs:
  CertificateId:
    Description: "Core Fantasy Certificate ID"
    Value: !Ref "Certificate"
    Export:
      Name: !Sub "CoreFantasy-Certificate"
