AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack for Core Fantasy.
Parameters:
  BucketName:
    Type: String
    Description: Bucket name in which deployment files reside.
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCName: !Ref 'AWS::StackName'
      TemplateURL: !Join
        - ''
        - - https://s3.amazonaws.com/
          - !Ref 'BucketName'
          - /VPC.json
  KubeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - https://s3.amazonaws.com/
          - !Ref 'BucketName'
          - /Kube.json
    DependsOn: VPCStack
  HttpdStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - https://s3.amazonaws.com/
          - !Ref 'BucketName'
          - /Httpd.json
    DependsOn:
      - VPCStack
      - KubeStack
