AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack for Core Fantasy.
Parameters:
  BucketName:
    Type: String
    Description: Bucket name in which deployment files reside.
  EC2KeyPairName:
    Type: String
    Description: EC2 Key pair name
  DBMasterPassword:
    Type: String
    Description: Master password for the Database (min 8 chars)
    NoEcho: true
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCName: !Ref 'AWS::StackName'
      TemplateURL: !Join
        - ''
        - - https://s3.amazonaws.com/
          - !Ref 'BucketName'
          - /VPC.yaml
  BastionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BucketName: !Ref 'BucketName'
        EC2KeyPairName: !Ref 'EC2KeyPairName'
      TemplateURL: !Join
      - ''
      - - https://s3.amazonaws.com/
        - !Ref 'BucketName'
        - /Bastion.yaml
    DependsOn: VPCStack
  KubeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - https://s3.amazonaws.com/
          - !Ref 'BucketName'
          - /Kube.yaml
    DependsOn: VPCStack
  DomainStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters: {}
      TemplateURL: !Join
      - ''
      - - https://s3.amazonaws.com/
        - !Ref 'BucketName'
        - /Domain.yaml
    DependsOn: VPCStack
  ELKStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EC2KeyPairName: !Ref 'EC2KeyPairName'
      TemplateURL: !Join
      - ''
      - - https://s3.amazonaws.com/
        - !Ref 'BucketName'
        - /ELK.yaml
    DependsOn:
      - VPCStack
      - KubeStack
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        MasterPassword: !Ref 'DBMasterPassword'
      TemplateURL: !Join
        - ''
        - - https://s3.amazonaws.com/
          - !Ref 'BucketName'
          - /Database.yaml
    DependsOn:
      - VPCStack
  WebServerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BucketName: !Ref 'BucketName'
        EC2KeyPairName: !Ref 'EC2KeyPairName'
      TemplateURL: !Join
        - ''
        - - https://s3.amazonaws.com/
          - !Ref 'BucketName'
          - /WebServer.yaml
    DependsOn:
      - VPCStack
      - KubeStack
      - DomainStack
  WorkerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EC2KeyPairName: !Ref 'EC2KeyPairName'
      TemplateURL: !Join
      - ''
      - - https://s3.amazonaws.com/
        - !Ref 'BucketName'
        - /Workers.yaml
    DependsOn:
    - VPCStack
    - KubeStack
    - DomainStack
