AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack for Core Fantasy.
Parameters:
  BucketName:
    Type: String
    Description: Bucket name in which deployment files reside.
  EC2KeyPairName:
    Type: String
    Description: EC2 Key pair name
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCName: !Ref 'AWS::StackName'
      TemplateURL: !Join
        - ''
        - - https://s3.amazonaws.com/
          - !Ref 'BucketName'
          - /VPC.yaml
  BastionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BucketName: !Ref 'BucketName'
        EC2KeyPairName: !Ref 'EC2KeyPairName'
      TemplateURL: !Join
      - ''
      - - https://s3.amazonaws.com/
        - !Ref 'BucketName'
        - /Bastion.yaml
    DependsOn: VPCStack
  KubeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join
        - ''
        - - https://s3.amazonaws.com/
          - !Ref 'BucketName'
          - /Kube.yaml
    DependsOn: VPCStack
  HttpdStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BucketName: !Ref 'BucketName'
      TemplateURL: !Join
        - ''
        - - https://s3.amazonaws.com/
          - !Ref 'BucketName'
          - /Httpd.yaml
    DependsOn:
      - VPCStack
      - KubeStack
